# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'f:\python_work\middle_task\ForgetDialog.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_ForgetDialog(object):
    def setupUi(self, ForgetDialog):
        ForgetDialog.setObjectName("ForgetDialog")
        ForgetDialog.resize(950, 580)
        ForgetDialog.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.GetbackBtn = QtWidgets.QPushButton(ForgetDialog)
        self.GetbackBtn.setGeometry(QtCore.QRect(350, 440, 260, 41))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.GetbackBtn.setFont(font)
        self.GetbackBtn.setStyleSheet("border-radius: 5px;\n"
"background-color: rgb(10, 200, 255);\n"
"color: rgb(255, 255, 255);")
        self.GetbackBtn.setObjectName("GetbackBtn")
        self.label_2 = QtWidgets.QLabel(ForgetDialog)
        self.label_2.setGeometry(QtCore.QRect(350, 265, 139, 16))
        self.label_2.setText("")
        self.label_2.setObjectName("label_2")
        self.lineEdit = QtWidgets.QLineEdit(ForgetDialog)
        self.lineEdit.setGeometry(QtCore.QRect(350, 230, 260, 30))
        self.lineEdit.setMinimumSize(QtCore.QSize(107, 0))
        self.lineEdit.setAutoFillBackground(False)
        self.lineEdit.setStyleSheet("border-radius: 5px;\n"
"border: 0.5px solid gray;")
        self.lineEdit.setObjectName("lineEdit")
        self.label_4 = QtWidgets.QLabel(ForgetDialog)
        self.label_4.setGeometry(QtCore.QRect(350, 322, 261, 20))
        self.label_4.setText("")
        self.label_4.setObjectName("label_4")
        self.lineEdit_4 = QtWidgets.QLineEdit(ForgetDialog)
        self.lineEdit_4.setGeometry(QtCore.QRect(350, 410, 260, 30))
        self.lineEdit_4.setStyleSheet("border-radius: 5px;\n"
"border: 0.5px solid gray;")
        self.lineEdit_4.setMaxLength(18)
        self.lineEdit_4.setEchoMode(QtWidgets.QLineEdit.Password)
        self.lineEdit_4.setObjectName("lineEdit_4")
        self.label_8 = QtWidgets.QLabel(ForgetDialog)
        self.label_8.setGeometry(QtCore.QRect(350, 237, 81, 16))
        self.label_8.setObjectName("label_8")
        self.lineEdit_2 = QtWidgets.QLineEdit(ForgetDialog)
        self.lineEdit_2.setGeometry(QtCore.QRect(350, 290, 101, 30))
        self.lineEdit_2.setStyleSheet("border-radius: 5px;\n"
"border: 0.5px solid gray;")
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.label_6 = QtWidgets.QLabel(ForgetDialog)
        self.label_6.setGeometry(QtCore.QRect(350, 390, 261, 20))
        self.label_6.setText("")
        self.label_6.setObjectName("label_6")
        self.lineEdit_3 = QtWidgets.QLineEdit(ForgetDialog)
        self.lineEdit_3.setGeometry(QtCore.QRect(350, 350, 260, 30))
        self.lineEdit_3.setStyleSheet("border-radius: 5px;\n"
"border: 0.5px solid gray;")
        self.lineEdit_3.setMaxLength(18)
        self.lineEdit_3.setEchoMode(QtWidgets.QLineEdit.Password)
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.frame = QtWidgets.QFrame(ForgetDialog)
        self.frame.setGeometry(QtCore.QRect(0, 0, 951, 70))
        self.frame.setStyleSheet("background-color: rgb(30, 180, 255);")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.pushButton = QtWidgets.QPushButton(self.frame)
        self.pushButton.setGeometry(QtCore.QRect(870, 0, 40, 30))
        self.pushButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton.setStyleSheet("border-radius: 3px;\n"
"border: 0.5px solid rgb(240,240,240);")
        self.pushButton.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/pic/images/02-1.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton.setIcon(icon)
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(self.frame)
        self.pushButton_2.setGeometry(QtCore.QRect(910, 0, 40, 30))
        self.pushButton_2.setAutoFillBackground(False)
        self.pushButton_2.setStyleSheet("border-radius: 3px;\n"
"border: 0.5px solid rgb(240,240,240);")
        self.pushButton_2.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/pic/images/02-2.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_2.setIcon(icon1)
        self.pushButton_2.setCheckable(False)
        self.pushButton_2.setChecked(False)
        self.pushButton_2.setAutoRepeat(False)
        self.pushButton_2.setAutoExclusive(False)
        self.pushButton_2.setFlat(False)
        self.pushButton_2.setObjectName("pushButton_2")
        self.label = QtWidgets.QLabel(self.frame)
        self.label.setGeometry(QtCore.QRect(30, 10, 141, 41))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setStyleSheet("color: rgb(255, 255, 255);")
        self.label.setObjectName("label")
        self.label_3 = QtWidgets.QLabel(self.frame)
        self.label_3.setGeometry(QtCore.QRect(170, 25, 91, 21))
        font = QtGui.QFont()
        font.setFamily("等线")
        font.setPointSize(12)
        self.label_3.setFont(font)
        self.label_3.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_3.setObjectName("label_3")
        self.frame_2 = QtWidgets.QFrame(ForgetDialog)
        self.frame_2.setGeometry(QtCore.QRect(0, 70, 950, 95))
        self.frame_2.setStyleSheet("background-color: rgb(250, 250, 250);")
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.label_5 = QtWidgets.QLabel(self.frame_2)
        self.label_5.setGeometry(QtCore.QRect(180, 30, 150, 5))
        self.label_5.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0.0995025, y1:0.5, x2:1, y2:0, stop:0 rgba(35, 201, 255, 255), stop:1 rgba(255, 255, 255, 255));")
        self.label_5.setText("")
        self.label_5.setObjectName("label_5")
        self.label_7 = QtWidgets.QLabel(self.frame_2)
        self.label_7.setGeometry(QtCore.QRect(120, 10, 50, 50))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_7.setFont(font)
        self.label_7.setAcceptDrops(False)
        self.label_7.setStyleSheet("background-color: rgb(10, 200, 255);\n"
"color: rgb(255, 255, 255);\n"
"border-radius: 25%;")
        self.label_7.setAlignment(QtCore.Qt.AlignCenter)
        self.label_7.setObjectName("label_7")
        self.label_9 = QtWidgets.QLabel(self.frame_2)
        self.label_9.setGeometry(QtCore.QRect(340, 10, 50, 50))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_9.setFont(font)
        self.label_9.setAcceptDrops(False)
        self.label_9.setStyleSheet("background-color: rgb(10, 200, 255);\n"
"color: rgb(255, 255, 255);\n"
"border-radius: 25%;")
        self.label_9.setAlignment(QtCore.Qt.AlignCenter)
        self.label_9.setObjectName("label_9")
        self.label_10 = QtWidgets.QLabel(self.frame_2)
        self.label_10.setGeometry(QtCore.QRect(400, 30, 150, 5))
        self.label_10.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0.0995025, y1:0.5, x2:1, y2:0, stop:0 rgba(35, 201, 255, 255), stop:1 rgba(255, 255, 255, 255));")
        self.label_10.setText("")
        self.label_10.setObjectName("label_10")
        self.label_11 = QtWidgets.QLabel(self.frame_2)
        self.label_11.setGeometry(QtCore.QRect(560, 10, 50, 50))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_11.setFont(font)
        self.label_11.setAcceptDrops(False)
        self.label_11.setStyleSheet("background-color: rgb(10, 200, 255);\n"
"color: rgb(255, 255, 255);\n"
"border-radius: 25%;")
        self.label_11.setAlignment(QtCore.Qt.AlignCenter)
        self.label_11.setObjectName("label_11")
        self.label_12 = QtWidgets.QLabel(self.frame_2)
        self.label_12.setGeometry(QtCore.QRect(620, 30, 150, 5))
        self.label_12.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0.0995025, y1:0.5, x2:1, y2:0, stop:0 rgba(35, 201, 255, 255), stop:1 rgba(255, 255, 255, 255));")
        self.label_12.setText("")
        self.label_12.setObjectName("label_12")
        self.label_13 = QtWidgets.QLabel(self.frame_2)
        self.label_13.setGeometry(QtCore.QRect(780, 10, 50, 50))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_13.setFont(font)
        self.label_13.setAcceptDrops(False)
        self.label_13.setStyleSheet("background-color: rgb(10, 200, 255);\n"
"color: rgb(255, 255, 255);\n"
"border-radius: 25%;")
        self.label_13.setAlignment(QtCore.Qt.AlignCenter)
        self.label_13.setObjectName("label_13")
        self.label_14 = QtWidgets.QLabel(self.frame_2)
        self.label_14.setGeometry(QtCore.QRect(115, 70, 81, 16))
        self.label_14.setObjectName("label_14")
        self.label_15 = QtWidgets.QLabel(self.frame_2)
        self.label_15.setGeometry(QtCore.QRect(330, 70, 81, 16))
        self.label_15.setObjectName("label_15")
        self.label_16 = QtWidgets.QLabel(self.frame_2)
        self.label_16.setGeometry(QtCore.QRect(556, 70, 61, 16))
        self.label_16.setObjectName("label_16")
        self.label_17 = QtWidgets.QLabel(self.frame_2)
        self.label_17.setGeometry(QtCore.QRect(774, 70, 81, 16))
        self.label_17.setObjectName("label_17")
        self.label_18 = QtWidgets.QLabel(ForgetDialog)
        self.label_18.setGeometry(QtCore.QRect(431, 236, 111, 20))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_18.setFont(font)
        self.label_18.setObjectName("label_18")
        self.label_19 = QtWidgets.QLabel(ForgetDialog)
        self.label_19.setGeometry(QtCore.QRect(540, 237, 111, 16))
        self.label_19.setObjectName("label_19")
        self.pushButton_3 = QtWidgets.QPushButton(ForgetDialog)
        self.pushButton_3.setGeometry(QtCore.QRect(480, 288, 101, 31))
        self.pushButton_3.setObjectName("pushButton_3")
        self.pushButton_4 = QtWidgets.QPushButton(ForgetDialog)
        self.pushButton_4.setGeometry(QtCore.QRect(350, 350, 141, 31))
        self.pushButton_4.setStyleSheet("border-radius: 5px;\n"
"background-color: rgb(10, 200, 255);\n"
"color: rgb(255, 255, 255);")
        self.pushButton_4.setObjectName("pushButton_4")
        self.pushButton_5 = QtWidgets.QPushButton(ForgetDialog)
        self.pushButton_5.setGeometry(QtCore.QRect(350, 350, 141, 31))
        self.pushButton_5.setStyleSheet("border-radius: 5px;\n"
"background-color: rgb(10, 200, 255);\n"
"color: rgb(255, 255, 255);")
        self.pushButton_5.setObjectName("pushButton_5")

        self.retranslateUi(ForgetDialog)
        self.pushButton_2.clicked.connect(ForgetDialog.close)
        self.pushButton.clicked.connect(ForgetDialog.showMinimized)
        QtCore.QMetaObject.connectSlotsByName(ForgetDialog)
        ForgetDialog.setTabOrder(self.lineEdit, self.lineEdit_2)
        ForgetDialog.setTabOrder(self.lineEdit_2, self.lineEdit_3)
        ForgetDialog.setTabOrder(self.lineEdit_3, self.lineEdit_4)
        ForgetDialog.setTabOrder(self.lineEdit_4, self.GetbackBtn)
        ForgetDialog.setTabOrder(self.GetbackBtn, self.pushButton)
        ForgetDialog.setTabOrder(self.pushButton, self.pushButton_2)

    def retranslateUi(self, ForgetDialog):
        _translate = QtCore.QCoreApplication.translate
        ForgetDialog.setWindowTitle(_translate("ForgetDialog", "找回密码"))
        self.GetbackBtn.setText(_translate("ForgetDialog", "重置密码"))
        self.lineEdit.setPlaceholderText(_translate("ForgetDialog", "请输入账号"))
        self.lineEdit_4.setPlaceholderText(_translate("ForgetDialog", "请再次输入新密码"))
        self.label_8.setText(_translate("ForgetDialog", "我们已经向"))
        self.lineEdit_2.setPlaceholderText(_translate("ForgetDialog", "请输入验证码"))
        self.lineEdit_3.setPlaceholderText(_translate("ForgetDialog", "请输入新密码"))
        self.label.setText(_translate("ForgetDialog", "Top安全中心"))
        self.label_3.setText(_translate("ForgetDialog", "重置密码"))
        self.label_7.setText(_translate("ForgetDialog", "1"))
        self.label_9.setText(_translate("ForgetDialog", "2"))
        self.label_11.setText(_translate("ForgetDialog", "3"))
        self.label_13.setText(_translate("ForgetDialog", "4"))
        self.label_14.setText(_translate("ForgetDialog", "输入账号"))
        self.label_15.setText(_translate("ForgetDialog", "验证手机号"))
        self.label_16.setText(_translate("ForgetDialog", "重置密码"))
        self.label_17.setText(_translate("ForgetDialog", "修改成功"))
        self.label_18.setText(_translate("ForgetDialog", "13511111111"))
        self.label_19.setText(_translate("ForgetDialog", "发送短信验证码"))
        self.pushButton_3.setText(_translate("ForgetDialog", "重新发送"))
        self.pushButton_4.setText(_translate("ForgetDialog", "确认"))
        self.pushButton_5.setText(_translate("ForgetDialog", "确认"))

import ForgetSource_rc
