# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'f:\python_work\middle_task\PersonInfo.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_PresonInfo(object):
    def setupUi(self, PresonInfo):
        PresonInfo.setObjectName("PresonInfo")
        PresonInfo.resize(770, 565)
        PresonInfo.setStyleSheet("background-color: rgb(250, 250, 250);")
        self.label = QtWidgets.QLabel(PresonInfo)
        self.label.setGeometry(QtCore.QRect(0, 0, 391, 571))
        self.label.setStyleSheet("")
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap(":/pic/images/04-04.jpg"))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        self.label_5 = QtWidgets.QLabel(PresonInfo)
        self.label_5.setEnabled(False)
        self.label_5.setGeometry(QtCore.QRect(450, 200, 30, 30))
        self.label_5.setText("")
        self.label_5.setPixmap(QtGui.QPixmap(":/pic/images/04-05.png"))
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(PresonInfo)
        self.label_6.setEnabled(False)
        self.label_6.setGeometry(QtCore.QRect(450, 260, 30, 30))
        self.label_6.setText("")
        self.label_6.setPixmap(QtGui.QPixmap(":/pic/images/04-06.png"))
        self.label_6.setScaledContents(True)
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(PresonInfo)
        self.label_7.setEnabled(False)
        self.label_7.setGeometry(QtCore.QRect(450, 320, 30, 30))
        self.label_7.setText("")
        self.label_7.setPixmap(QtGui.QPixmap(":/pic/images/04-07.png"))
        self.label_7.setScaledContents(True)
        self.label_7.setObjectName("label_7")
        self.label_8 = QtWidgets.QLabel(PresonInfo)
        self.label_8.setEnabled(False)
        self.label_8.setGeometry(QtCore.QRect(450, 390, 30, 30))
        self.label_8.setText("")
        self.label_8.setPixmap(QtGui.QPixmap(":/pic/images/04-08.png"))
        self.label_8.setScaledContents(True)
        self.label_8.setObjectName("label_8")
        self.label_9 = QtWidgets.QLabel(PresonInfo)
        self.label_9.setGeometry(QtCore.QRect(500, 208, 151, 16))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift SemiLight")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.label_9.setFont(font)
        self.label_9.setObjectName("label_9")
        self.label_10 = QtWidgets.QLabel(PresonInfo)
        self.label_10.setGeometry(QtCore.QRect(500, 265, 171, 21))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.label_10.setFont(font)
        self.label_10.setObjectName("label_10")
        self.pushButton_4 = QtWidgets.QPushButton(PresonInfo)
        self.pushButton_4.setGeometry(QtCore.QRect(660, 460, 81, 28))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.pushButton_4.setFont(font)
        self.pushButton_4.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_4.setStyleSheet("border:0px;\n"
"color: rgb(74, 148, 222);")
        self.pushButton_4.setObjectName("pushButton_4")
        self.label_11 = QtWidgets.QLabel(PresonInfo)
        self.label_11.setGeometry(QtCore.QRect(500, 328, 181, 16))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift SemiLight")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.label_11.setFont(font)
        self.label_11.setObjectName("label_11")
        self.label_12 = QtWidgets.QLabel(PresonInfo)
        self.label_12.setGeometry(QtCore.QRect(500, 398, 181, 16))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift SemiLight")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.label_12.setFont(font)
        self.label_12.setObjectName("label_12")
        self.pushButton_3 = QtWidgets.QPushButton(PresonInfo)
        self.pushButton_3.setGeometry(QtCore.QRect(740, 0, 30, 30))
        self.pushButton_3.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_3.setStyleSheet("background-color:transparent;")
        self.pushButton_3.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/pic/images/04-03.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_3.setIcon(icon)
        self.pushButton_3.setObjectName("pushButton_3")
        self.pushButton_2 = QtWidgets.QPushButton(PresonInfo)
        self.pushButton_2.setGeometry(QtCore.QRect(700, 0, 30, 30))
        self.pushButton_2.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_2.setStyleSheet("background-color:transparent;")
        self.pushButton_2.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/pic/images/04-02.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_2.setIcon(icon1)
        self.pushButton_2.setObjectName("pushButton_2")
        self.label_2 = QtWidgets.QLabel(PresonInfo)
        self.label_2.setGeometry(QtCore.QRect(450, 60, 81, 81))
        self.label_2.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.label_2.setStyleSheet("\n"
"")
        self.label_2.setText("")
        self.label_2.setPixmap(QtGui.QPixmap(":/pic/images/04-01.png"))
        self.label_2.setScaledContents(True)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(PresonInfo)
        self.label_3.setGeometry(QtCore.QRect(540, 60, 221, 41))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setStyleSheet("\n"
"background-color: transparent;")
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(PresonInfo)
        self.label_4.setGeometry(QtCore.QRect(540, 120, 231, 16))
        self.label_4.setStyleSheet("\n"
"background-color:transparent;")
        self.label_4.setObjectName("label_4")

        self.retranslateUi(PresonInfo)
        self.pushButton_2.clicked.connect(PresonInfo.showMinimized)
        self.pushButton_3.clicked.connect(PresonInfo.close)
        QtCore.QMetaObject.connectSlotsByName(PresonInfo)

    def retranslateUi(self, PresonInfo):
        _translate = QtCore.QCoreApplication.translate
        PresonInfo.setWindowTitle(_translate("PresonInfo", "PersonInfoWin"))
        self.label_9.setText(_translate("PresonInfo", "10001"))
        self.label_10.setText(_translate("PresonInfo", "男"))
        self.pushButton_4.setText(_translate("PresonInfo", "编辑资料"))
        self.label_11.setText(_translate("PresonInfo", "1889-06-23"))
        self.label_12.setText(_translate("PresonInfo", "13588888888"))
        self.label_3.setText(_translate("PresonInfo", "ayuan"))
        self.label_4.setText(_translate("PresonInfo", "time is roughly"))

import PersonInfoSource_rc
