# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'f:\python_work\middle_task\RegisterDialog.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtCore import QRegExp
from PyQt5.QtGui import QRegExpValidator

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(950, 580)
        Dialog.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"")
        self.usernameLe = QtWidgets.QLineEdit(Dialog)
        self.usernameLe.setGeometry(QtCore.QRect(500, 145, 360, 30))
        self.usernameLe.setMinimumSize(QtCore.QSize(107, 0))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.usernameLe.setFont(font)
        self.usernameLe.setAutoFillBackground(False)
        self.usernameLe.setStyleSheet("border-radius: 5px;\n"
"border: 0.5px solid gray;")
        self.usernameLe.setObjectName("usernameLe")
        self.usernameLb = QtWidgets.QLabel(Dialog)
        self.usernameLb.setGeometry(QtCore.QRect(500, 180, 139, 16))
        self.usernameLb.setText("")
        self.usernameLb.setObjectName("usernameLb")
        self.RegisterBtn = QtWidgets.QPushButton(Dialog)
        self.RegisterBtn.setGeometry(QtCore.QRect(500, 520, 360, 41))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.RegisterBtn.setFont(font)
        self.RegisterBtn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.RegisterBtn.setStyleSheet("border-radius: 5px;\n"
"color: rgb(255, 255, 255);\n"
"background-color: rgb(10,200, 255);")
        self.RegisterBtn.setObjectName("RegisterBtn")
        self.phonenumberLe = QtWidgets.QLineEdit(Dialog)
        self.phonenumberLe.setGeometry(QtCore.QRect(500, 420, 360, 30))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.phonenumberLe.setFont(font)
        self.phonenumberLe.setStyleSheet("border-radius: 5px;\n"
"border: 0.5px solid gray;")
        self.phonenumberLe.setObjectName("phonenumberLe")
        self.label_4 = QtWidgets.QLabel(Dialog)
        self.label_4.setGeometry(QtCore.QRect(500, 335, 271, 16))
        self.label_4.setText("")
        self.label_4.setObjectName("label_4")
        self.label_6 = QtWidgets.QLabel(Dialog)
        self.label_6.setGeometry(QtCore.QRect(500, 400, 139, 16))
        self.label_6.setText("")
        self.label_6.setObjectName("label_6")
        self.passwordLe = QtWidgets.QLineEdit(Dialog)
        self.passwordLe.setGeometry(QtCore.QRect(500, 300, 360, 30))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.passwordLe.setFont(font)
        self.passwordLe.setStyleSheet("border-radius: 5px;\n"
"border: 0.5px solid gray;")
        self.passwordLe.setMaxLength(16)
        self.passwordLe.setEchoMode(QtWidgets.QLineEdit.Password)
        self.passwordLe.setObjectName("passwordLe")
        self.ensureLe = QtWidgets.QLineEdit(Dialog)
        self.ensureLe.setGeometry(QtCore.QRect(500, 360, 360, 30))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.ensureLe.setFont(font)
        self.ensureLe.setStyleSheet("border-radius: 5px;\n"
"border: 0.5px solid gray;")
        self.ensureLe.setMaxLength(16)
        self.ensureLe.setEchoMode(QtWidgets.QLineEdit.Password)
        self.ensureLe.setObjectName("ensureLe")
        self.dateEdit = QtWidgets.QDateEdit(Dialog)
        self.dateEdit.setGeometry(QtCore.QRect(500, 240, 361, 30))
        self.dateEdit.setStyleSheet("border-radius: 5px;\n"
"border: 0.5px solid gray;\n"
"")
        self.dateEdit.setCalendarPopup(True)
        self.dateEdit.setObjectName("dateEdit")
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(0, 0, 394, 580))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap(":/pic/images/01-1.jpg"))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        self.checkBox = QtWidgets.QCheckBox(Dialog)
        self.checkBox.setGeometry(QtCore.QRect(500, 490, 301, 19))
        self.checkBox.setChecked(False)
        self.checkBox.setTristate(False)
        self.checkBox.setObjectName("checkBox")
        self.label_2 = QtWidgets.QLabel(Dialog)
        self.label_2.setGeometry(QtCore.QRect(500, 30, 191, 41))
        self.label_2.setStyleSheet("font: 75 18pt \"微软雅黑\";")
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(Dialog)
        self.label_3.setGeometry(QtCore.QRect(500, 80, 171, 41))
        self.label_3.setStyleSheet("font: 75 14pt \"等线\";")
        self.label_3.setObjectName("label_3")
        self.pushButton = QtWidgets.QPushButton(Dialog)
        self.pushButton.setGeometry(QtCore.QRect(870, 0, 40, 30))
        self.pushButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton.setStyleSheet("border-radius: 3px;\n"
"border: 0.5px solid rgb(220,220,220);")
        self.pushButton.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/pic/images/01-6.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton.setIcon(icon)
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(Dialog)
        self.pushButton_2.setGeometry(QtCore.QRect(910, 0, 40, 30))
        self.pushButton_2.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_2.setAutoFillBackground(False)
        self.pushButton_2.setStyleSheet("border-radius: 3px;\n"
"border: 0.5px solid rgb(220,220,220);")
        self.pushButton_2.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/pic/images/01-5.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_2.setIcon(icon1)
        self.pushButton_2.setCheckable(False)
        self.pushButton_2.setChecked(False)
        self.pushButton_2.setAutoRepeat(False)
        self.pushButton_2.setAutoExclusive(False)
        self.pushButton_2.setFlat(False)
        self.pushButton_2.setObjectName("pushButton_2")
        self.radioBtn1 = QtWidgets.QRadioButton(Dialog)
        self.radioBtn1.setGeometry(QtCore.QRect(500, 205, 41, 19))
        self.radioBtn1.setChecked(True)
        self.radioBtn1.setObjectName("radioBtn1")
        self.radioBtn2 = QtWidgets.QRadioButton(Dialog)
        self.radioBtn2.setGeometry(QtCore.QRect(550, 205, 41, 19))
        self.radioBtn2.setObjectName("radioBtn2")
        self.label_5 = QtWidgets.QLabel(Dialog)
        self.label_5.setGeometry(QtCore.QRect(500, 180, 81, 16))
        self.label_5.setObjectName("label_5")
        self.label_7 = QtWidgets.QLabel(Dialog)
        self.label_7.setGeometry(QtCore.QRect(580, 180, 111, 16))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.label_8 = QtWidgets.QLabel(Dialog)
        self.label_8.setGeometry(QtCore.QRect(690, 180, 111, 16))
        self.label_8.setObjectName("label_8")
        self.label_9 = QtWidgets.QLabel(Dialog)
        self.label_9.setGeometry(QtCore.QRect(500, 210, 181, 16))
        self.label_9.setObjectName("label_9")
        self.lineEdit = QtWidgets.QLineEdit(Dialog)
        self.lineEdit.setGeometry(QtCore.QRect(500, 270, 181, 31))
        self.lineEdit.setObjectName("lineEdit")
        self.pushButton_3 = QtWidgets.QPushButton(Dialog)
        self.pushButton_3.setGeometry(QtCore.QRect(702, 270, 91, 31))
        self.pushButton_3.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_3.setObjectName("pushButton_3")
        self.pushButton_4 = QtWidgets.QPushButton(Dialog)
        self.pushButton_4.setGeometry(QtCore.QRect(500, 330, 181, 31))
        self.pushButton_4.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_4.setStyleSheet("border-radius: 5px;\n"
"color: rgb(255, 255, 255);\n"
"background-color: rgb(10,200, 255);")
        self.pushButton_4.setObjectName("pushButton_4")
        self.label_10 = QtWidgets.QLabel(Dialog)
        self.label_10.setGeometry(QtCore.QRect(500, 190, 171, 31))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_10.setFont(font)
        self.label_10.setObjectName("label_10")
        self.label_11 = QtWidgets.QLabel(Dialog)
        self.label_11.setGeometry(QtCore.QRect(500, 240, 121, 16))
        self.label_11.setObjectName("label_11")
        self.label_12 = QtWidgets.QLabel(Dialog)
        self.label_12.setGeometry(QtCore.QRect(620, 232, 171, 31))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_12.setFont(font)
        self.label_12.setObjectName("label_12")
        self.label_13 = QtWidgets.QLabel(Dialog)
        self.label_13.setGeometry(QtCore.QRect(500, 280, 241, 16))
        self.label_13.setObjectName("label_13")
        self.pushButton_5 = QtWidgets.QPushButton(Dialog)
        self.pushButton_5.setGeometry(QtCore.QRect(500, 330, 181, 31))
        self.pushButton_5.setStyleSheet("border-radius: 5px;\n"
"color: rgb(255, 255, 255);\n"
"background-color: rgb(10,200, 255);")
        self.pushButton_5.setObjectName("pushButton_5")
        self.usernameLe.raise_()
        self.usernameLb.raise_()
        self.RegisterBtn.raise_()
        self.phonenumberLe.raise_()
        self.label_4.raise_()
        self.label_6.raise_()
        self.passwordLe.raise_()
        self.ensureLe.raise_()
        self.dateEdit.raise_()
        self.checkBox.raise_()
        self.label_2.raise_()
        self.label_3.raise_()
        self.pushButton.raise_()
        self.pushButton_2.raise_()
        self.radioBtn1.raise_()
        self.radioBtn2.raise_()
        self.label_5.raise_()
        self.label_7.raise_()
        self.label_8.raise_()
        self.label_9.raise_()
        self.lineEdit.raise_()
        self.pushButton_3.raise_()
        self.pushButton_4.raise_()
        self.label_10.raise_()
        self.label_11.raise_()
        self.label_12.raise_()
        self.label_13.raise_()
        self.pushButton_5.raise_()
        self.label.raise_()

        self.retranslateUi(Dialog)
        self.pushButton_2.clicked.connect(Dialog.close)
        self.pushButton.clicked.connect(Dialog.showMinimized)
        QtCore.QMetaObject.connectSlotsByName(Dialog)
        Dialog.setTabOrder(self.usernameLe, self.radioBtn1)
        Dialog.setTabOrder(self.radioBtn1, self.radioBtn2)
        Dialog.setTabOrder(self.radioBtn2, self.dateEdit)
        Dialog.setTabOrder(self.dateEdit, self.passwordLe)
        Dialog.setTabOrder(self.passwordLe, self.ensureLe)
        Dialog.setTabOrder(self.ensureLe, self.phonenumberLe)
        Dialog.setTabOrder(self.phonenumberLe, self.checkBox)
        Dialog.setTabOrder(self.checkBox, self.RegisterBtn)
        Dialog.setTabOrder(self.RegisterBtn, self.pushButton)
        Dialog.setTabOrder(self.pushButton, self.pushButton_2)

        #我的设置
        self.dateEdit.setStyleSheet("""
        QDateEdit{border-radius: 3px;border: 0.5px solid gray;}
        QDateEdit::down-arrow{image:url(":/pic/images/01-7.png");}
        QDateEdit::drop-down {
            subcontrol-origin: padding;
            subcontrol-position: top right;
            width: 26px;
            border-left-width: 0.5px;
            border-left-color: darkgray;
            border-left-style: solid;
            border-top-right-radius: 3px;
            border-bottom-right-radius: 3px;}
        """)
        #设置密码字符和验证器
        reg = QRegExp("[^\u4e00-\u9fa5]+")
        pValidator = QRegExpValidator(self)
        pValidator.setRegExp(reg)
        self.passwordLe.setValidator(pValidator)
        self.ensureLe.setValidator(pValidator)
        #设置手机号码验证和长度
        reg = QRegExp("[0-9]{11}")
        pValidator = QRegExpValidator(self)
        pValidator.setRegExp(reg)
        self.phonenumberLe.setValidator(pValidator) 
        
    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "注册账号"))
        self.usernameLe.setPlaceholderText(_translate("Dialog", "请输入用户名"))
        self.RegisterBtn.setText(_translate("Dialog", "注册"))
        self.phonenumberLe.setPlaceholderText(_translate("Dialog", "请输入11位手机号码"))
        self.passwordLe.setPlaceholderText(_translate("Dialog", "请输入8-19位数字、字母、字符密码组合"))
        self.ensureLe.setPlaceholderText(_translate("Dialog", "请再次输入密码"))
        self.dateEdit.setDisplayFormat(_translate("Dialog", "yyyy-MM-dd"))
        self.checkBox.setText(_translate("Dialog", "我已阅读并同意相关服务条款和隐私政策"))
        self.label_2.setText(_translate("Dialog", "欢迎注册TOP"))
        self.label_3.setText(_translate("Dialog", "轻松交流每一天"))
        self.radioBtn1.setText(_translate("Dialog", "男"))
        self.radioBtn2.setText(_translate("Dialog", "女"))
        self.label_5.setText(_translate("Dialog", "我们已经向"))
        self.label_7.setText(_translate("Dialog", "18388303743"))
        self.label_8.setText(_translate("Dialog", "发送短信验证码"))
        self.label_9.setText(_translate("Dialog", "请输入验证码完成注册："))
        self.pushButton_3.setText(_translate("Dialog", "重新发送"))
        self.pushButton_4.setText(_translate("Dialog", "完成注册"))
        self.label_10.setText(_translate("Dialog", "恭喜您，注册成功!!!"))
        self.label_11.setText(_translate("Dialog", "您的Top账号为："))
        self.label_12.setText(_translate("Dialog", "10000"))
        self.label_13.setText(_translate("Dialog", "您将使用账号 + 密码登录TopChat。"))
        self.pushButton_5.setText(_translate("Dialog", "我知道了"))

import RegisterSource_rc
